name: "pull_request"

on:
  workflow_dispatch:
  pull_request:
    types:
      - "opened"
      - "edited"
      - "reopened"
      - "ready_for_review"
      - "review_requested"

jobs:
  check:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "c032/gha-go@main"
