name: "push"

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  check:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "c032/gha-go@main"

  interactions-api-docker-image:
    runs-on: "ubuntu-latest"
    needs:
      - "check"
    permissions:
      contents: "read"
      packages: "write"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "c032/gha-docker@main"
        with:
          image-name: "${{ github.repository }}-interactions-api"
          registry-username: "${{ github.actor }}"
          registry-password: "${{ secrets.GITHUB_TOKEN }}"
          dockerfile: "docker/interactions-api.dockerfile"
